//Autogenerated
package com.vision4j.completion;

import java.io.InputStream;
import java.io.File;
import java.net.URL;
import java.io.IOException;
import com.vision4j.utils.*;

/**
 * Basic contract that every image completion model should fulfill.
 */
public interface Completion {

    CompletionResult complete(InputStream image, InputStream mask) throws IOException;

    CompletionResult complete(InputStream image, File mask) throws IOException;

    CompletionResult complete(InputStream image, byte[] mask) throws IOException;

    CompletionResult complete(InputStream image, URL mask) throws IOException;

    CompletionResult complete(File image, InputStream mask) throws IOException;

    CompletionResult complete(File image, File mask) throws IOException;

    CompletionResult complete(File image, byte[] mask) throws IOException;

    CompletionResult complete(File image, URL mask) throws IOException;

    CompletionResult complete(byte[] image, InputStream mask) throws IOException;

    CompletionResult complete(byte[] image, File mask) throws IOException;

    CompletionResult complete(byte[] image, byte[] mask) throws IOException;

    CompletionResult complete(byte[] image, URL mask) throws IOException;

    CompletionResult complete(URL image, InputStream mask) throws IOException;

    CompletionResult complete(URL image, File mask) throws IOException;

    CompletionResult complete(URL image, byte[] mask) throws IOException;

    CompletionResult complete(URL image, URL mask) throws IOException;
}
