//Autogenerated
package com.vision4j.segmentation;

import java.io.InputStream;
import java.io.File;
import java.net.URL;
import java.io.IOException;
import com.vision4j.utils.*;

/**
 * Basic contract that every image segmentation model should fulfill.
 */
public interface Segmentation extends CategoriesProblem {

    SegmentationResult segment(InputStream image) throws IOException;

    SegmentationResult segment(File image) throws IOException;

    SegmentationResult segment(byte[] image) throws IOException;

    SegmentationResult segment(URL image) throws IOException;
}
