//Autogenerated
package com.vision4j.classification;

import io.grpc.ManagedChannel;
import static com.vision4j.utils.Constants.*;

public class GrpcImageNetClassification extends GrpcClassifier {

    public GrpcImageNetClassification() {
        super(IMAGENET_CATEGORIES);
    }

    public GrpcImageNetClassification(ManagedChannel channel) {
        super(IMAGENET_CATEGORIES, channel);
    }

    public GrpcImageNetClassification(String host, int port) {
        super(IMAGENET_CATEGORIES, host, port);
    }
}
