//Autogenerated
package com.vision4j.detection;

import io.grpc.ManagedChannel;
import static com.vision4j.utils.Constants.*;

public class CocoDetection extends GrpcDetection {

    public CocoDetection() {
        super(COCO_CATEGORIES);
    }

    public CocoDetection(ManagedChannel channel) {
        super(COCO_CATEGORIES, channel);
    }

    public CocoDetection(String host, int port) {
        super(COCO_CATEGORIES, host, port);
    }
}
