//Autogenerated
package com.vision4j.segmentation;

import io.grpc.ManagedChannel;
import static com.vision4j.utils.Constants.*;

public class PascalVOC2012GrpcSegmentation extends GrpcSegmentation {

    public PascalVOC2012GrpcSegmentation() {
        super(PASCAL_VOC_2012_CATEGORIES);
    }

    public PascalVOC2012GrpcSegmentation(ManagedChannel channel) {
        super(PASCAL_VOC_2012_CATEGORIES, channel);
    }

    public PascalVOC2012GrpcSegmentation(String host, int port) {
        super(PASCAL_VOC_2012_CATEGORIES, host, port);
    }
}
