//Autogenerated
package com.vision4j.completion;

import io.grpc.ManagedChannel;
import static com.vision4j.utils.Constants.*;

public class GimpGrpcCompletion extends GrpcCompletion {

    public GimpGrpcCompletion() {
        super();
    }

    public GimpGrpcCompletion(ManagedChannel channel) {
        super(channel);
    }

    public GimpGrpcCompletion(String host, int port) {
        super(host, port);
    }
}
