//Autogenerated
package com.vision4j.completion;

import io.grpc.ManagedChannel;
import static com.vision4j.utils.Constants.*;

public class Places2Completion extends GrpcCompletion {

    public Places2Completion() {
        super();
    }

    public Places2Completion(ManagedChannel channel) {
        super(channel);
    }

    public Places2Completion(String host, int port) {
        super(host, port);
    }
}
