//Autogenerated
package com.vision4j.face.detection;

import java.io.InputStream;
import java.io.File;
import java.net.URL;
import java.io.IOException;
import com.vision4j.utils.*;

/**
 * Basic contract that every image face_detection model should fulfill.
 */
public interface FaceDetection {

    FaceDetectionResult detect(InputStream image) throws IOException;

    FaceDetectionResult detect(File image) throws IOException;

    FaceDetectionResult detect(byte[] image) throws IOException;

    FaceDetectionResult detect(URL image) throws IOException;
}
