//Autogenerated
package com.vision4j.classification;

import java.io.InputStream;
import java.io.File;
import java.net.URL;
import java.io.IOException;
import com.vision4j.utils.*;

/**
 * Basic contract that every image classification model should fulfill.
 */
public interface ImageClassifier extends CategoriesProblem {

    Category predict(InputStream image) throws IOException;

    Category predict(File image) throws IOException;

    Category predict(byte[] image) throws IOException;

    Category predict(URL image) throws IOException;
}
