//Autogenerated
package com.vision4j.detection;

import java.io.InputStream;
import java.io.File;
import java.net.URL;
import java.io.IOException;
import com.vision4j.utils.*;

/**
 * Basic contract that every image detection model should fulfill.
 */
public interface Detection extends CategoriesProblem {

    DetectionResult detect(InputStream image) throws IOException;

    DetectionResult detect(File image) throws IOException;

    DetectionResult detect(byte[] image) throws IOException;

    DetectionResult detect(URL image) throws IOException;
}
